# Generated by Django 2.2.13 on 2020-12-17 14:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_registry_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, overwrite=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="refinement",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, overwrite=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="refinement",
            name="xsd_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
